# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 461)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Volumeup = QtWidgets.QPushButton(self.centralwidget)
        self.Volumeup.setGeometry(QtCore.QRect(30, 130, 75, 23))
        self.Volumeup.setObjectName("Volumeup")
        self.Volumedown = QtWidgets.QPushButton(self.centralwidget)
        self.Volumedown.setGeometry(QtCore.QRect(30, 170, 75, 23))
        self.Volumedown.setObjectName("Volumedown")
        self.Channelup = QtWidgets.QPushButton(self.centralwidget)
        self.Channelup.setGeometry(QtCore.QRect(220, 130, 75, 23))
        self.Channelup.setObjectName("Channelup")
        self.Channeldown = QtWidgets.QPushButton(self.centralwidget)
        self.Channeldown.setGeometry(QtCore.QRect(220, 160, 75, 23))
        self.Channeldown.setObjectName("Channeldown")
        self.Mute = QtWidgets.QPushButton(self.centralwidget)
        self.Mute.setGeometry(QtCore.QRect(120, 260, 75, 23))
        self.Mute.setObjectName("Mute")
        self.Power = QtWidgets.QPushButton(self.centralwidget)
        self.Power.setGeometry(QtCore.QRect(120, 220, 75, 23))
        self.Power.setObjectName("Power")
        self.Volume = QtWidgets.QLabel(self.centralwidget)
        self.Volume.setGeometry(QtCore.QRect(26, 49, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Volume.setFont(font)
        self.Volume.setText("")
        self.Volume.setObjectName("Volume")
        self.Channel = QtWidgets.QLabel(self.centralwidget)
        self.Channel.setGeometry(QtCore.QRect(200, 50, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Channel.setFont(font)
        self.Channel.setText("")
        self.Channel.setObjectName("Channel")
        self.Powr = QtWidgets.QLabel(self.centralwidget)
        self.Powr.setGeometry(QtCore.QRect(130, 410, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.Powr.setFont(font)
        self.Powr.setText("")
        self.Powr.setObjectName("Powr")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Volumeup.setText(_translate("MainWindow", "Volume +"))
        self.Volumedown.setText(_translate("MainWindow", "Volume -"))
        self.Channelup.setText(_translate("MainWindow", "Channel +"))
        self.Channeldown.setText(_translate("MainWindow", "Channel -"))
        self.Mute.setText(_translate("MainWindow", "Mute"))
        self.Power.setText(_translate("MainWindow", "Power"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
